// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sat May 18 14:05:10 2024

abilities abilities_inst
(
	.speed(speed_sig) ,	// input [2:0] speed_sig
	.pipe_passed(pipe_passed_sig) ,	// input  pipe_passed_sig
	.pixel_row(pixel_row_sig) ,	// input [9:0] pixel_row_sig
	.pixel_column(pixel_column_sig) ,	// input [9:0] pixel_column_sig
	.pipe1_x_in(pipe1_x_in_sig) ,	// input [10:0] pipe1_x_in_sig
	.ability1_type(ability1_type_sig) ,	// output [2:0] ability1_type_sig
	.r(r_sig) ,	// output [3:0] r_sig
	.g(g_sig) ,	// output [3:0] g_sig
	.b(b_sig) ,	// output [3:0] b_sig
	.ability1_on(ability1_on_sig) 	// output  ability1_on_sig
);

